[package]
name = "watchai-mock"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
watchai-core = { path = "../watchai-core" }
watchai-ipc = { path = "../watchai-ipc" }
tokio.workspace = true
zbus.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
nix.workspace = true
